/**
 * API Configuration (Git Ignored)
 * Place your obfuscated or plain-text keys here.
 */
window.CONFIG = {
    SUPABASE_URL: "KTE5XSB/bHo8PE8yLihLSEVDRzs3Lkk9KjY8P2tePjU4T1NDVxgiKg==",
    SUPABASE_ANON_KEY: "JDwHRTECIDwdLGcCECNkA35bfzIMI39mJgAcZAxGOx0PbngJHFM4Dz1OYAgqGjsPVy8dG0VrXXRMGxYEXhorCTkILGR9DDQYB2lcWjMmGndlIRsTKiBDAS8DagdGVmEtMQREJCwgOGs2dxgMb2RfdkdUc3EkYRAPMwwKFEQELxwefFpZAg8/JlUcASAmGyh7fyYaZAR9WHd1Cxl8YgsXEGYLHntrK2RRb1xDc3cMRyIwLTNmA1wdaBR7ZH9fQAAHBV4ABxsQBXF+PithT2t+ew==",
    OPENROUTER_API_KEY: "Mi5gQiFoNWR/c0hzdjoVBVZQUyUhfkw1dHNnYnQUc3NpHVBVBwd1cXtJZyZ0YWNzHSl3PRlWBQQPcyApGGRxdWUxdh96dzpIAw==",
    WEBHOOK_PATH: "bjIoTzsqLD59NkI4"
};
